# Generated by Django 2.2.3 on 2019-08-06 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.URLField(blank=True, max_length=999, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='firstname', max_length=255)),
                ('last_name', models.CharField(default='lastname', max_length=255)),
                ('username', models.CharField(default='username', max_length=255)),
                ('email', models.EmailField(help_text='Required', max_length=255, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('password', models.CharField(max_length=100)),
                ('profile', models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=999, null=True)),
                ('text', models.CharField(blank=True, max_length=999, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('collaborator', models.CharField(blank=True, max_length=255, null=True)),
                ('is_archive', models.BooleanField(default=False)),
                ('is_Trash', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('reminder', models.DateTimeField(auto_now=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
