# Generated by Django 2.2.3 on 2019-07-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='firstname', max_length=255)),
                ('last_name', models.CharField(default='lastname', max_length=255)),
                ('username', models.CharField(default='username', max_length=255)),
                ('email', models.EmailField(help_text='Required', max_length=255)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
