# Generated by Django 2.2.3 on 2019-07-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='label',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
