# Generated by Django 2.2.3 on 2019-07-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0002_auto_20190725_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
