# Generated by Django 2.2.3 on 2019-07-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0003_auto_20190725_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='is_Trash',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='is_archive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='is_pinned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
