# Generated by Django 2.2.3 on 2019-07-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0004_auto_20190725_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='label',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='reminder',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='text',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
