# Generated by Django 2.2.3 on 2019-08-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0006_auto_20190807_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='label',
            field=models.ManyToManyField(blank=True, to='fundooapp.Label'),
        ),
    ]
