# Generated by Django 2.2.3 on 2019-08-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20190816_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='reminder',
            field=models.DateField(blank=True, null=True),
        ),
    ]
