# Generated by Django 2.2.3 on 2019-08-24 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20190824_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='collaborator',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_collaborator', to=settings.AUTH_USER_MODEL),
        ),
    ]
